# Generated by Django 5.2.3 on 2025-06-21 05:47

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charaimagemodel',
            name='charaimage',
            field=models.FileField(upload_to='images/', validators=[chat.models.validate_image_or_video]),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='system_dialogue',
            field=models.CharField(max_length=255),
        ),
    ]
